"""mo-doc-writer skill for Phase 4 artifacts generation."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app.retrieval.incremental_scope import load_path_mappings


FORBIDDEN_BODY_MARKERS = [
    "ai-generated",
    "generated by ai",
    "chatgpt",
    "由ai",
    "由ai生成",
]


@dataclass
class WriterInput:
    prev_tag: str
    new_tag: str
    evidence_bundle: dict[str, Any]
    path_mapping_file: Path


@dataclass
class WriterOutput:
    doc_patch_diff: str
    change_summary_md: str
    claims: dict[str, Any]


def build_author_prompt(writer_input: WriterInput) -> str:
    """Build anti-hallucination prompt for external LLM author plugins."""
    return (
        "你只能基于给定证据生成文档补丁。\n"
        "禁止使用任何外部知识、历史记忆或猜测。\n"
        "每条 claim 必须包含 docs_path、evidence.code_path、evidence.reason。\n"
        f"prev_tag={writer_input.prev_tag}\n"
        f"new_tag={writer_input.new_tag}\n"
        "请输出结构化结果：doc_patch_diff, change_summary_md, claims。"
    )


def run_writer_skill(writer_input: WriterInput) -> WriterOutput:
    claims = _build_claims(writer_input)
    _validate_whitelist(claims, writer_input.path_mapping_file)
    doc_patch_diff = _build_patch_diff(
        claims,
        writer_input.prev_tag,
        writer_input.new_tag,
        writer_input.evidence_bundle,
    )
    _validate_doc_body_clean(doc_patch_diff)
    change_summary_md = _build_change_summary(claims, writer_input.prev_tag, writer_input.new_tag)

    return WriterOutput(
        doc_patch_diff=doc_patch_diff,
        change_summary_md=change_summary_md,
        claims={
            "prev_tag": writer_input.prev_tag,
            "new_tag": writer_input.new_tag,
            "claim_count": len(claims),
            "claims": claims,
        },
    )


def _build_claims(writer_input: WriterInput) -> list[dict[str, Any]]:
    retrieval_scope = writer_input.evidence_bundle.get("retrieval_scope", [])
    if not isinstance(retrieval_scope, list):
        raise ValueError("invalid evidence_bundle.retrieval_scope: expected list")

    claims: list[dict[str, Any]] = []
    claim_seq = 0
    for item in retrieval_scope:
        if not isinstance(item, dict):
            raise ValueError("invalid retrieval scope item: expected dict")
        if not item.get("in_scope", False):
            continue
        code_path = str(item.get("code_path", ""))
        mapped_docs = item.get("mapped_docs", [])
        if not isinstance(mapped_docs, list):
            raise ValueError("invalid mapped_docs: expected list")
        for mapping in mapped_docs:
            if not isinstance(mapping, dict):
                raise ValueError("invalid mapped_doc item: expected dict")
            claim_seq += 1
            docs_path = str(mapping.get("docs_path", ""))
            topic = str(mapping.get("topic", ""))
            claim = {
                "claim_id": f"C{claim_seq:03d}",
                "topic": topic,
                "docs_path": docs_path,
                "description": f"Code changes under {code_path} require doc review for {topic}.",
                "evidence": {
                    "code_path": code_path,
                    "source": "evidence_bundle.retrieval_scope",
                    "reason": f"{code_path} is mapped to {docs_path} and changed in the diff scope",
                },
            }
            claims.append(claim)
    return claims


def _validate_whitelist(claims: list[dict[str, Any]], path_mapping_file: Path) -> None:
    allowed_paths = {
        str(item.get("docs_path", ""))
        for item in load_path_mappings(path_mapping_file)
        if str(item.get("docs_path", ""))
    }
    for claim in claims:
        docs_path = str(claim.get("docs_path", ""))
        if docs_path not in allowed_paths:
            raise ValueError(f"writer generated docs path outside whitelist: {docs_path}")


def _build_patch_diff(
    claims: list[dict[str, Any]],
    prev_tag: str,
    new_tag: str,
    evidence_bundle: dict[str, Any],
) -> str:
    if not claims:
        return ""

    rendered: list[str] = []
    unique_docs_paths = sorted({str(c["docs_path"]) for c in claims})
    commit_subjects = _collect_commit_subjects(evidence_bundle)
    changed_files = _collect_changed_files(evidence_bundle)
    for docs_path in unique_docs_paths:
        summary_lines = _build_patch_summary_lines(prev_tag, new_tag, commit_subjects, changed_files)
        rendered.extend(
            [
                f"diff --git a/{docs_path} b/{docs_path}",
                f"--- a/{docs_path}",
                f"+++ b/{docs_path}",
                f"@@ -0,0 +1,{len(summary_lines)} @@",
                *[f"+{line}" for line in summary_lines],
                "",
            ]
        )
    return "\n".join(rendered).rstrip() + "\n"


def _collect_commit_subjects(evidence_bundle: dict[str, Any]) -> list[str]:
    commits = evidence_bundle.get("commits", [])
    if not isinstance(commits, list):
        return []
    subjects: list[str] = []
    for item in commits:
        if not isinstance(item, dict):
            continue
        subject = str(item.get("subject", "")).strip()
        if subject:
            subjects.append(subject)
    return subjects


def _collect_changed_files(evidence_bundle: dict[str, Any]) -> list[str]:
    changed = evidence_bundle.get("changed_files", [])
    if not isinstance(changed, list):
        return []
    return [str(path).strip() for path in changed if str(path).strip()]


def _build_patch_summary_lines(
    prev_tag: str,
    new_tag: str,
    commit_subjects: list[str],
    changed_files: list[str],
) -> list[str]:
    lines = [
        f"Update notes for release range {prev_tag}..{new_tag}.",
        "Aligned with verified evidence from changed code paths.",
    ]
    if commit_subjects:
        lines.append(f"Representative commit: {_normalize_text(commit_subjects[0])}.")
    if changed_files:
        lines.append(f"Representative changed file: {_normalize_text(changed_files[0])}.")
    return lines


def _normalize_text(value: str, max_len: int = 180) -> str:
    cleaned = "".join(ch for ch in value if ch.isprintable())
    cleaned = " ".join(cleaned.split())
    if not cleaned:
        return "<unavailable>"
    if len(cleaned) <= max_len:
        return cleaned
    return f"{cleaned[:max_len]}..."


def _build_change_summary(claims: list[dict[str, Any]], prev_tag: str, new_tag: str) -> str:
    lines = [
        f"# Change Summary ({prev_tag} -> {new_tag})",
        "",
    ]
    if not claims:
        lines.extend(
            [
                "No in-scope documentation updates were generated from current evidence.",
                "",
            ]
        )
        return "\n".join(lines)

    lines.append("## Proposed Documentation Updates")
    for claim in claims:
        lines.append(
            f"- `{claim['docs_path']}`: {claim['description']} (topic: `{claim['topic']}`)"
        )
    lines.append("")
    return "\n".join(lines)


def _validate_doc_body_clean(doc_patch_diff: str) -> None:
    for line in doc_patch_diff.splitlines():
        if not line.startswith("+") or line.startswith("+++"):
            continue
        lowered = line.lower()
        for marker in FORBIDDEN_BODY_MARKERS:
            if marker in lowered:
                raise ValueError(f"doc patch contains forbidden AI marker: {marker}")
