"""mo-doc-reviewer skill for claim-by-claim validation."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any, Literal


@dataclass
class ReviewerInput:
    doc_patch_diff: str
    claims: dict[str, Any]
    evidence_bundle: dict[str, Any]


@dataclass
class ReviewerOutput:
    decision: Literal["pass", "fail"]
    review_report: dict[str, Any]
    blocking_issues: list[str] = field(default_factory=list)


FORBIDDEN_BODY_MARKERS = [
    "ai-generated",
    "generated by ai",
    "chatgpt",
    "由ai",
    "由ai生成",
]


def build_reviewer_prompt(reviewer_input: ReviewerInput) -> str:
    """Build independent-verification prompt for external reviewer plugins."""
    return (
        "你是独立审核者，必须逐条核验 claims 与证据映射。\n"
        "若证据不足、docs_path 不在 patch、或 code_path 映射不匹配，必须拒绝。\n"
        "输出 decision/comments/blocking_issues/review_report/verification_map。"
    )


def run_reviewer_skill(reviewer_input: ReviewerInput) -> ReviewerOutput:
    claim_results: list[dict[str, Any]] = []
    blocking_issues: list[str] = []

    claims = reviewer_input.claims.get("claims", [])
    if not isinstance(claims, list):
        raise ValueError("claims.claims must be a list")

    claim_count = reviewer_input.claims.get("claim_count")
    if isinstance(claim_count, int) and claim_count != len(claims):
        blocking_issues.append(
            f"claim_count mismatch: expected {claim_count}, actual {len(claims)}"
        )

    evidence_paths, evidence_doc_mappings = _collect_evidence_paths_and_mappings(
        reviewer_input.evidence_bundle
    )
    patch_docs_paths = _collect_patch_docs_paths(reviewer_input.doc_patch_diff)
    _check_forbidden_markers(reviewer_input.doc_patch_diff, blocking_issues)

    for claim in claims:
        result = _review_claim(
            claim=claim,
            evidence_paths=evidence_paths,
            evidence_doc_mappings=evidence_doc_mappings,
            patch_docs_paths=patch_docs_paths,
        )
        claim_results.append(result)
        if result["status"] == "fail":
            blocking_issues.append(result["reason"])

    decision: Literal["pass", "fail"] = "fail" if blocking_issues else "pass"
    review_report = {
        "checked_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "decision": decision,
        "claim_results": claim_results,
        "blocking_issues": blocking_issues,
    }
    return ReviewerOutput(
        decision=decision,
        review_report=review_report,
        blocking_issues=blocking_issues,
    )


def _collect_evidence_paths_and_mappings(
    evidence_bundle: dict[str, Any],
) -> tuple[set[str], dict[str, set[str]]]:
    retrieval_scope = evidence_bundle.get("retrieval_scope", [])
    if not isinstance(retrieval_scope, list):
        raise ValueError("evidence_bundle.retrieval_scope must be a list")
    paths: set[str] = set()
    mappings: dict[str, set[str]] = {}
    for item in retrieval_scope:
        if not isinstance(item, dict):
            continue
        code_path = str(item.get("code_path", "")).strip()
        if code_path:
            paths.add(code_path)
            mapped_docs = item.get("mapped_docs", [])
            if isinstance(mapped_docs, list):
                docs_paths = {
                    str(doc.get("docs_path", "")).strip()
                    for doc in mapped_docs
                    if isinstance(doc, dict) and str(doc.get("docs_path", "")).strip()
                }
                if docs_paths:
                    mappings[code_path] = docs_paths
    return paths, mappings


def _collect_patch_docs_paths(doc_patch_diff: str) -> set[str]:
    docs_paths: set[str] = set()
    for line in doc_patch_diff.splitlines():
        if not line.startswith("diff --git "):
            continue
        # Format: diff --git a/<path> b/<path>
        parts = line.split()
        if len(parts) >= 4 and parts[2].startswith("a/"):
            docs_paths.add(parts[2][2:])
    return docs_paths


def _review_claim(
    claim: dict[str, Any],
    evidence_paths: set[str],
    evidence_doc_mappings: dict[str, set[str]],
    patch_docs_paths: set[str],
) -> dict[str, str]:
    claim_id = str(claim.get("claim_id", "")).strip() or "unknown"
    docs_path = str(claim.get("docs_path", "")).strip()
    evidence = claim.get("evidence", {})
    code_path = str(evidence.get("code_path", "") if isinstance(evidence, dict) else "").strip()

    if not docs_path:
        return {
            "claim_id": claim_id,
            "status": "fail",
            "reason": f"{claim_id}: missing docs_path",
        }
    if docs_path not in patch_docs_paths:
        return {
            "claim_id": claim_id,
            "status": "fail",
            "reason": f"{claim_id}: docs_path {docs_path} not found in doc_patch.diff",
        }
    if not code_path or code_path not in evidence_paths:
        return {
            "claim_id": claim_id,
            "status": "fail",
            "reason": f"{claim_id}: evidence code_path {code_path or '<empty>'} not found in evidence bundle",
        }
    allowed_docs = evidence_doc_mappings.get(code_path, set())
    if docs_path not in allowed_docs:
        return {
            "claim_id": claim_id,
            "status": "fail",
            "reason": f"{claim_id}: docs_path {docs_path} not mapped from evidence code_path {code_path}",
        }

    return {
        "claim_id": claim_id,
        "status": "pass",
        "reason": "verified",
    }


def _check_forbidden_markers(doc_patch_diff: str, blocking_issues: list[str]) -> None:
    for line in doc_patch_diff.splitlines():
        if not line.startswith("+") or line.startswith("+++"):
            continue
        lowered = line.lower()
        for marker in FORBIDDEN_BODY_MARKERS:
            if marker in lowered:
                blocking_issues.append(f"forbidden AI marker detected in doc patch: {marker}")
